### PR TITLE
Modify the object version of toInclude

### LINKED ISSUE #82: (object) toInclude does not work as expected
According to the doc, `(object) toInclude` uses `assert.deepEqual` by default. I expect the following assertion should fail but it does not.

```
expect({ a: { b: 4 }}).toInclude({ a: {}})
```

### PR DESCRIPTION
**Pull request by wuct**
This PR introduces following changes:

* Traverse both enumerable  name keys and enumerable  symbol keys.

  `expect({a: 1}).toInclude({[Symbol()]: 1}) // fail`

* Always pass a assertion with an empty object as an expected value.

  `expect({a: 1}).toInclude({}) // pass`

BREAKING CHANGE: compare an empty object property to its corresponding actual property.

  Before:
    `expect({}).toInclude({a: {}}) // pass`

  After:
    `expect({a: 1}).toInclude({a: {}}) // fail`

Closes #82

### CODE REVIEW

**Comment by wuct** [comment]
It is a rebased and squashed version of #83. I also rewrote the commit message.

**Comment by ljharb** [comment]
@wuct Thanks! It'd have been preferable to modify the original PR instead of opening a new one, but this will do :-)

**Comment by wuct** [comment]
@ljharb Thank you, too! I have learnt a lot from you 😊

**Comment by ljharb** [comment]
@wuct afaik, only pushing a branch deletion to the remote will trigger the PR to close. You need to instead, actually force push, in order to update a PR in-place.

**Comment by ljharb** [comment]
@mjackson @elado Do you consider this a breaking change, or a bugfix on the initial `toInclude` support?

I originally classified it as a breaking change because it will throw in cases where it previously did not - however, in those cases, I suspect users *want* it to throw, meaning this would be revealing failing tests.

**Comment by elado** [comment]
From #82:
> According to the doc, (object) toInclude uses assert.deepEqual by default. I expect the following assertion should fail but it does not.
> `expect({ a: { b: 4 }}).toInclude({ a: {}})`

I don't expect this to fail. The original object includes a key `a` and the original `object.a` value contains `{}`. It's not supposed to deep equal the inner values but keep matching keys and values, in this case the `expected.a` is an object with no keys, so there's nothing to compare, therefore, it shouldn't fail.

**Comment by ljharb** [comment]
@elado in your situation i would not expect it to fail. However, if `a` was a non-object on the LHS and an empty object on the RHS, i would: in other words, `expect({ a: 1 }).toInclude({ a: {} })` should fail.

**Comment by ljharb** [comment]
Actually, perhaps not - as long as the value on the LHS is not `null` or `undefined`, it might indeed become autoboxed - ie, `expect({ a: 'b' }).toInclude({ a: { length: 1 } })` should pass.

If @elado concurs, then @wuct, can you change this so that an empty object on the RHS only fails (for any key) when the LHS is `null` or `undefined`?

**Comment by elado** [comment]
I think `expect({ a: 1 }).toInclude({ a: {} })` should fail (simple type check, compare partial objects only of both are objects) and also `expect({ a: 'b' }).toInclude({ a: { length: 1 } })` (can't compare a string with an object - I don't think this case is common)

So what might be missing is the type check on both values.

**Comment by ljharb** [comment]
That seems equally reasonable to me.

**Comment by wuct** [comment]
I agree with @elado. We should compare partial objects only when both types are `"object"`. I can do this modification.

**Comment by wuct** [comment]
@ljharb @elado @mjackson I just updated the code according to our discussion. Please let me know if there is any thing not expected.

File: modules/__tests__/toInclude-test.js [hunk 1]
```diff
@@ -56,6 +60,52 @@ describe('toInclude', () => {
...
+      }).toNotThrow()
+    })
+  }
+
+  if (typeof Symbol === 'function') {
+    const symbol = Symbol()
+
+    it('does not throw when an object contains an expected object with a symbol key', () => {
+      expect(() => {
+        expect({ [symbol]: 1, b: 2 }).toInclude({ [symbol]: 1 })
```
Comment (ljharb) [inline modules/__tests__/toInclude-test.js]: Symbols are supported in plenty of environments where computed property keys are not - could you construct the objects the old-fashioned way?

Comment (ljharb) [inline modules/__tests__/toInclude-test.js]: atually nevermind, i forgot this is using babel

File: modules/ownKeys.js [hunk 2]
```diff
@@ -0,0 +1,19 @@
+import objectKeys from 'object-keys'
+
+const ownKeys = (object) => {
```
Comment (mjackson) [inline modules/ownKeys.js]: Perhaps we could call this `ownEnumerableKeys` to avoid confusing it with `Reflect.ownKeys`?

Comment (ljharb) [inline modules/ownKeys.js]: isn't it meant to be a polyfill for Reflect.ownKeys?

Comment (mjackson) [inline modules/ownKeys.js]: @ljharb Not AFAICT. It restricts the result of `Reflect.ownKeys` to enumerable keys.

Comment (ljharb) [inline modules/ownKeys.js]: ah, k

**Comment by wuct** [comment]
Thanks for merging :)
